channels: 
  - conda-forge
dependencies:
  - python=3.7*
  - numpy==1.19.1
  - pandas==1.1.1
  - xarray==0.16.0
  - fsspec==0.8.0
  - matplotlib 
  - gdrivefs==0+untagged.18.g540a55f
  - os
  - time 
  - glob
  - warnings
  - skimage== 0.17.2 #.io
  - viewer #via skimage
  - matplotlib.image as mpimg
  - matplotlib.pyplot import figure
  - from IPython.display import Video
  - from IPython import display
  - from matplotlib import animation
  - PIL==7.2.0
  - PIL import Image
  - IPython.display import Image
  - IPython.display import display
  - IPython.core.display import HTML
  - matplotlib.pyplot 
  - matplotlib import ticker, cm

  