channels: 
  - conda-forge
dependencies:
  - python=3.7*
  - numpy
  - pandas
  - xarray
  - matplotlib 
  - os
  - time 
  - glob
  - warnings
  - skimage.io
  - skimage.viewer
  - matplotlib.image as mpimg
  - matplotlib.pyplot import figure
  - from IPython.display import Video
  - from matplotlib import animation
  - PIL
  - PIL import Image
  - IPython.display import Image
  - IPython.display import display
  - IPython.core.display import HTML
  - matplotlib.pyplot as plt 
from matplotlib import ticker, cm
%matplotlib inline  
from IPython import display
display.set_matplotlib_formats('retina')
  