channels: 
  - conda-forge
dependencies:
  - python=3.7*
  - numpy==1.19.1
  - pandas==1.1.1
  - xarray==0.16.0
  - fsspec==0.8.0
  - matplotlib==3.3.1
  #- matplotlib.pyplot 
  #- matplotlib import ticker, cm
  #- matplotlib.image as mpimg
  #- matplotlib.pyplot import figure
  #- from matplotlib import animation
  
  - PIL==7.2.0
  #- PIL import Image
  
  - gdrivefs  #==0+untagged.18.g540a55f
  
  - IPython==7.18.1
  #- from IPython.display import Video
  #- from IPython import display
  #- IPython.display import Image
  #- IPython.display import display
  #- IPython.core.display import HTML
  

  - skimage==0.17.2 
  #-import skimage.io as io
  #-import skimage.viewer

  #Older
  #- os
  #- glob
  #- time 
  #- warnings
  